# Generated by Django 4.1.3 on 2022-12-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_account_tutorial_tutorial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_image',
            field=models.ImageField(blank=True, upload_to='main/img'),
        ),
    ]
