# Generated by Django 4.1.3 on 2022-12-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_tutorial_tutorial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='main/img')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.tutorial')),
            ],
        ),
    ]
