# Generated by Django 4.1.3 on 2022-12-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_tutorialimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialimage',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
